version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - app.env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    env_file:
      - app.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: